### ISSUE TITLE
[Feature Suggestion] Add Talents from Character Sheet

### ISSUE THREAD

**Issue by sehlura** [Mezryss/FVTT-Genesys#107]
It would be extremely valuable and useful for players to have the ability to add talents to their character sheet with an "Add+" button.
-  Would it be possible to create such a button that opens a new dialogue window that lists all the Talent objects available in the current World?
- Could such a dialogue list the talent objects in a way that can be sorted by Name and Tier, searched, or even filtered by the same?

It seems like a big ask, but such a feature would be incredible!

**Comment by Assembling-Kings** [comment]
The workflow right now is very similar. If you create a bunch of talents and keep them in a compendium that the players can see, they can simply drag and drop from it into their character's sheet. And if you create multiple folders for each tier you can get them sorted alphabetically per tier. What exactly is it that you would like to see differently?
