### ISSUE TITLE
Categorize Item types with optgroups

### ISSUE THREAD

**Issue by Mezryss** [Mezryss/FVTT-Genesys#11]
It'd be great to go with an approach similar to what the Pathfinder 2E devs do with items: sort them into optgroups in the type selection drop-down.

![image](https://user-images.githubusercontent.com/124085763/216121346-9622d24e-2ec0-4808-9dc2-f9b3b7d7db9b.png)

**Comment by Assembling-Kings** [comment]
^ Sorry for all that noise, I kept pushing and noticing a simple change I needed to make/merge from my other branch.

**Comment by Mezryss** [comment]
No problem, I don't get notifications for all those pushes so no harm done.

Closing this out since I merged your PR
