### ISSUE TITLE
Failed to activate modified skill compendium

### ISSUE THREAD

**Issue by andreihu** [Mezryss/FVTT-Genesys#121]
I have tried to update the skill compendium as written in https://github.com/Mezryss/FVTT-Genesys/discussions/50 .

I have duplicated the core skill compendium and saved it under a new name.

![compendium](https://github.com/Mezryss/FVTT-Genesys/assets/11031118/75c75c13-5d72-44a6-a207-bafacd288fbc)

I have modified the configuration to point to the new file.

![config](https://github.com/Mezryss/FVTT-Genesys/assets/11031118/c7e343d2-ef02-43d1-83c5-e47749f692f6)

When i try to create a new Character i got the following message:

![problem](https://github.com/Mezryss/FVTT-Genesys/assets/11031118/776e87cf-7ca2-4bb2-be03-c2496a1d420c)

I am pretty sure that i have made a mistake, but i don't know how to debug this.

**Comment by Assembling-Kings** [comment]
The string you use for the skill compendium should be `world.cxskills`. Notice that I used "world" and not the world name.

**Comment by andreihu** [comment]
Ahh, i see. That's a stupid mistake from my side!

Thanks for the help, the problem is solved!
