### ISSUE TITLE
attributes translation not make

### ISSUE THREAD

**Issue by ZolOnTheNet** [Mezryss/FVTT-Genesys#127]
Thank for you job !

I regret to inform you that the translation of Characteristics is not correct in the latest release, as shown in the attachment. I don't know why, as the correspondence is done in English with the same path "Genesys.Characteristics.Brawn" for example.

However, I did put the translation (the rest of the page is correctly translated).
![mauvaiseTraduction](https://github.com/Mezryss/FVTT-Genesys/assets/103053124/197e5521-1558-479d-be82-3d024594413f)

Rem : I use the distribution pack (automatic update)

**Comment by Assembling-Kings** [comment]
Is this happening for every sheet or it it specific to only Character sheets?

**Comment by ZolOnTheNet** [comment]
For every sheet, alas. under GM and player (for Character sheets).

**Comment by Assembling-Kings** [comment]
I just tested it and it looks fine to me (after manually adding the language option):

**_FVTT v10_**
![image](https://github.com/Mezryss/FVTT-Genesys/assets/1728535/e98857df-af19-4f7b-a10f-2c2ac4300965)
**_FVTT v11_**
![image](https://github.com/Mezryss/FVTT-Genesys/assets/1728535/c419991b-19c3-4833-b64d-deef10daa490)
