### ISSUE TITLE
I find why the translation didn't make for the standard distribution : foundryvtt error. Just for information

### ISSUE THREAD

**Issue by ZolOnTheNet** [Mezryss/FVTT-Genesys#128]
I find where the error come from !
in the game the variable in french language : 
game.i18n.translations.Genesys.Characteristics 
Object { Brawn: "Brawn", Agility: "Agility", Intellect: "Intellect", Cunning: "Cunning", Willpower: "Willpower", Presence: "Presence" }
​Agility: "Agility"
​Brawn: "Brawn"
​Cunning: "Cunning"
​Intellect: "Intellect"
​Presence: "Presence"
​Willpower: "Willpower"
​<prototype>: Object { … }

and if you see the order of load of lang JSON :
Foundry VTT | Loaded localization file systems/genesys/lang/fr.json [foundry.js:7533:15](https://xxxxx.yyyyyyy.fr/scripts/foundry.js)
Foundry VTT | Loaded localization file modules/fr-core/fr.json [foundry.js:7533:15](https://xxxxx.yyyyyyy.fr/scripts/foundry.js)
Foundry VTT | Loaded localization file systems/genesys/lang/en.json [foundry.js:7533:15](https://xxxxx.yyyyyyy.fr/scripts/foundry.js)
Foundry VTT | Loaded localization file lang/en.json [foundry.js:7533:15](https://xxxxx.yyyyyyy.fr/scripts/foundry.js)

Something go wrong and crash the game.i18n.translations.Genesys.Characteristics (and some other,  Tabs it's ok but, SkillCategory )
if I modify the variable into Brawn to Vigueur, I have the good result... Strange no ? I try to find why the program crush this particular object.
I hope I was correct explain...

**Comment by ZolOnTheNet** [comment]
To help french, pour aider les français qui souhaiterai changer les bonnes valeurs de traduction vous pouvez faire une marcro "Script" avec le code ci dessous :
game.i18n.translations.Genesys.Characteristics.Brawn = "Vigueur"
game.i18n.translations.Genesys.Characteristics.Agility = "Agilité"
game.i18n.translations.Genesys.Characteristics.Intellect = "Intelligence"
game.i18n.translations.Genesys.Characteristics.Cunning = "Ruse"
game.i18n.translations.Genesys.Characteristics.Willpower = "Volonté"
game.i18n.translations.Genesys.Characteristics.Presence = "Présence"

**Comment by Assembling-Kings** [comment]
I can't simply reproduce this problem. Here's a test world on FVTT v11.
![image](https://github.com/Mezryss/FVTT-Genesys/assets/1728535/10048c3d-565b-4a5e-87bb-cf278e0641e0)
![image](https://github.com/Mezryss/FVTT-Genesys/assets/1728535/5353b2d3-c07b-43c7-9253-1103f64cdf79)

- What version of FoundryVTT are you using?
- What version of the system are you using?
- Can you give me GM access to your world or send a backup of it?

**Comment by ZolOnTheNet** [comment]
Thank for you answer. I have the v.11 build 325. And you answer give me a indice and, i find the reason : it's a module ! I have desatived all module and I have the good translation. Thank again for you job and for the answer...

I have made a HUD Module, and I have a make a error  : it's now correcting and recieves my Apologize

**Comment by Assembling-Kings** [comment]
Good thing it was a simple fix. 😄
