### ISSUE TITLE
Dragging skills not working for players

### ISSUE THREAD

**Issue by User52525252** [Mezryss/FVTT-Genesys#137]
Hello. 
As Players we can't add skills into newly created items/archetypes/carrers. Thus the GM needs to make all archetypes and careers by themselves 
This makes character creattion rather inconvenient.
Are there any workarounds possible ?

**Comment by Assembling-Kings** [comment]
The GM can give users the permission to create items via the "Permission Configuration" window: https://foundryvtt.com/article/users/
