### ISSUE TITLE
[Request] Dice Pool Modification Skills

### ISSUE THREAD

**Issue by zane5015** [Mezryss/FVTT-Genesys#160]
With the addition of [#152](https://github.com/Mezryss/FVTT-Genesys/pull/152) will there be a way to have active effects for custom made skills (some examples including unique magics and combat skills) in the future?

**Comment by Assembling-Kings** [comment]
Could you elaborate what you mean? Because currently the list of skills that show up on the active effect dropdown is the list of skills present on the configured skill compendium.

**Comment by zane5015** [comment]
I'm asking if there is a way to add more options to the dropdown in terms of custom made skills. For an example in a game I'm currently in we are using vehicles extensively along with the [Mechasys](https://www.drivethrurpg.com/en/product/351561/Mechasys) Core rulebook. In it we use skills such as Gunnery(Cannons) and Gunnery(Missiles) for weapon checks, however we can't use the Dice pool modification for those skills so I'm asking if there we can add those skills along with other custom ones to the dropdown for pool modification toggles.

**Comment by Assembling-Kings** [comment]
So like I mentioned:
>  ...the list of skills that show up on the active effect dropdown is the list of skills present on the configured skill compendium.

For example, here's a custom skills list:
![image](https://github.com/Mezryss/FVTT-Genesys/assets/1728535/b66984ee-4e7e-43fb-b2c2-587e74510558)

And here it is on the dropdown:
![image](https://github.com/Mezryss/FVTT-Genesys/assets/1728535/cb0dfd37-5c51-4ecb-9929-0b3f4747de4e)

And finally here is on the pool:
![image](https://github.com/Mezryss/FVTT-Genesys/assets/1728535/13a08d1a-7e38-4621-8e7f-da6c4dfec412)

**Comment by zane5015** [comment]
Ah I see, apologies for wasting your time on this. didn't fully realize that I could just add skills into a list like that for it to work. Thank you for your time in responding to me on this topic. If I may ask, how would I get the system to read the newly created compendium?

**Comment by Assembling-Kings** [comment]
No problem, follow the "Starting with Skills" section from this guide: https://github.com/Mezryss/FVTT-Genesys/discussions/50

Note that when it mentions the word `world`, it means the actual word, not the name of your world.
