### ISSUE TITLE
Abilities and Nemesis dd not  have option to support Adversary Upgrade Rule

### ISSUE THREAD

**Issue by Lyinggod** [Mezryss/FVTT-Genesys#164]
Adversary is an ability that upgrades  the difficulty of a check when attacking a nemesis. This option does not appear in talents, abilities, or on the Nemesis sheet. Additionally, this option should upgrade attack rolls when a nemesis token is targeted on the canvas.

**Comment by Assembling-Kings** [comment]
Implemented by #179
