### ISSUE TITLE
Compatibility with Foundry v12

### ISSUE THREAD

**Issue by bogus34** [Mezryss/FVTT-Genesys#169]
Can it be compatible with Foundry version 12?

**Comment by Assembling-Kings** [comment]
It's in my radar to do so but not for a while. I've been super busy in real life during the past month and I expect this month (and the next) to be the same. But yeah, I always want to keep the system up to date so I'll be deprecating support for the previous versions (v10, v11) when I get to do this.

**Comment by Assembling-Kings** [comment]
Completed as part of #177
