### ISSUE TITLE
Talent Page typo

### ISSUE THREAD

**Issue by ForestofAeshe** [Mezryss/FVTT-Genesys#188]
When you insert talents with the time of activation as Incidental or Incidental, Out of Turn: sheet spells Incidental as incEdental (Caps for emphasis). 
<img width="52" alt="image" src="https://github.com/user-attachments/assets/77968285-94fe-411d-83a2-b5e555910479">

**Comment by Assembling-Kings** [comment]
So those are taken directly from the Talent activation field, which means that the typo is on the Talent itself.
