### ISSUE TITLE
HArd point and damage State 

### ISSUE THREAD

**Issue by Roxas21** [Mezryss/FVTT-Genesys#189]
Greetings, are there any plans on adding the Hard point statistic and Damage state of items?

**Comment by Assembling-Kings** [comment]
Damage states is already implemented. Click on the face emoji next to an item in a character's inventory. Left click to damage, Right click to "un-damage".

Hard Points will be implemented whenever I get around to implement the Attachments rules.

**Comment by Roxas21** [comment]
Alright thanks! i never actually saw that emoji. But thanks for the info :)
