### ISSUE TITLE
Hide Story Points from UI?

### ISSUE THREAD

**Issue by lucky13games** [Mezryss/FVTT-Genesys#196]
I am sooo thankful for your work on enabling Genesys via the foundry vtt!   When playing virtually the display of the story points (player vs gm) is useful, but in person I am casting our maps to a tv on the table, and there is no way to remove these UI elements so they're always on the screen. I have scoured the configuration options everywhere but don't see a place to disable these.  Is it possible to make these fall under the usual UI rules and allow them to be hidden?  That way when I am displaying a map they're not obscuring anything. 

Thanks for any help or modifications in advance!

**Comment by Assembling-Kings** [comment]
There is no setting or option that lets you disable the Story Point UI but you can disable it this way (I do it myself for my games during certain moments):
1. Install the [[Custom CSS]](https://foundryvtt.com/packages/custom-css/) module
2. Go to the module settings and add the following
```css
.genesys.story-point-tracker {
  visibility: hidden !important;
}
```

I hope this alternative works good enough for you.

**Comment by lucky13games** [comment]
Ooooh! I am traveling at the moment, but will give this a shot when I return home tomorrow.  MUCH appreciated for the prompt and clear reply!

**Comment by lucky13games** [comment]
Stupendous Success! Thank you!
