### ISSUE TITLE
Item Qualities can't be added to Armor

### ISSUE THREAD

**Issue by Torticute** [Mezryss/FVTT-Genesys#25]
What it says in the title. There is no Qualities field on Armor item either:
![image](https://user-images.githubusercontent.com/30007326/222928905-14fa55b9-5dfc-46dd-ad79-9804cc113de8.png)

**Comment by Mezryss** [comment]
![image](https://user-images.githubusercontent.com/124085763/222930965-e8ff5678-0930-4649-a7fe-32c37955c1e4.png)

Implemented
