### ISSUE TITLE
Capitalization should match on all text

### ISSUE THREAD

**Issue by Lyinggod** [Mezryss/FVTT-Genesys#29]
This is rather low priority but, I think, worth mentioning. Some fonts use only upper case characters, while other fonts allow for mixed case. An example of this is items names. If incorrect letter case is used, then it can only be noticed outside of the areas that only allow uppercase. Case errors should be immediately obvious when typing. The following image provides an example. In this example, the error would be obvious once the title is stored but not while actively typing.
![image](https://user-images.githubusercontent.com/16379736/222933738-4109afe5-cfba-429e-b758-5b27c056d1b7.png)

**Comment by Mezryss** [comment]
I'm not sure what can be done for this outside of dropping Bebas Neue (I don't think that forcing all-caps where the names appear elsewhere would look good), but I'll see if I can find a happy alternative.

**Comment by Lyinggod** [comment]
Perhaps there is an edit font for when the field has a focus and a display font for the rest of the time. Either a completely different font or using a form of small caps with the Roboto font to show lowercase.
