### ISSUE TITLE
Adversaries lack motivations fields

### ISSUE THREAD

**Issue by mkesselm** [Mezryss/FVTT-Genesys#30]
Rivals should have strength and flaw, and nemeses should have all four similarly to PCs. But would probably make sense to just have all four as options for all adversary types.

**Comment by Mezryss** [comment]
Do you have a source for this? I don't see anything where that's spelled out explicitly for any NPCs' stat blocks.

If this is just something that you like including for your own games, there's no reason you can't note them in the NPC's descriptive text.

**Comment by mkesselm** [comment]
It's built into how structured social encounters work, but these are also in the SotC blocks. They might be in the SotB cards, too? Not entirely sure. But it wasn't something that was part of the standard block in CRB (not in EPG either).

**Comment by Mezryss** [comment]
I'm looking through SotC right now and I don't see them in any of the blocks, same with SotB.

Since they don't have any automatable mechanics to worry about I think for now it's best to put them in the NPC's descriptive text box. I can revisit again in the future if needed.

**Comment by mkesselm** [comment]
Oh....right. It's from the SotC adversary cards. Wonder if they're going to continue the trend in EotI. Anyway, I still think it's worth including on the sheets to avoid clutter, but fair enough if it's not a priority for you!

**Comment by JNogaj** [comment]
Wouldn't call it priority but that is indeed a QoL change. Motivations are missing from the general statblocks because they are meant to be more individualistic.
