### ISSUE TITLE
Cannot delete quality after editing on item

### ISSUE THREAD

**Issue by Lyinggod** [Mezryss/FVTT-Genesys#32]
I placed an item with a quality on a character sheet. I then edited the text of original quality in the items tab. When I attempted to delete the original unedited quality from the item on the character sheet, i get the following error:
![image](https://user-images.githubusercontent.com/16379736/222955597-996d1bea-ac88-4659-939e-e1c3206c3d9d.png)

This seems to only affect items on character sheets. If I make these edits to the weapon in the items tab, there is no error.

**Comment by Mezryss** [comment]
I'll create a new release with the fix for this later today. Gonna wait in case there are a couple other small and easy bugs I have the energy for today.
