### ISSUE TITLE
Using Genesys font turns dice symbols black/white

### ISSUE THREAD

**Issue by JohanFalt** [Mezryss/FVTT-Genesys#34]
I was using the Genesys font in the description field of a quality mainly for testing but as I use genesys font B it is black, same as genesys font S.

**Comment by Mezryss** [comment]
It isn't a color font.

I haven't populated the wiki yet (too much going on in life right now), but you can insert symbols and dice with the following enrichers:

`@sym[satfhd]` =>  **S**uccess, **A**dvantage, **T**riumph, **F**ailure, t**H**reat, **D**espair
`@dice[apbdcs]` => **A**bility, **P**roficiency, **B**oost, **D**ifficulty, **C**hallenge, **S**etback
`@dice[col,gybprk]` => **G**reen, **Y**ellow, **B**lue, **P**urple, **R**ed, blac**K**
