### ISSUE TITLE
Talents appearing twice on Character sheet

### ISSUE THREAD

**Issue by SheriffDann** [Mezryss/FVTT-Genesys#35]
Foundry Version 10
Build 291
Genesys 0.1.4
Active Modules 1 (Forge)

When adding a Talent from the Item library to the character sheet it adds the talent twice.
This is only happening to talents marked with (Active) 

In the journal there is only one addition and XP cost for the talent. And in the Talent Tier counts it's only counting one instance of the talent (see screenshot)

![image](https://user-images.githubusercontent.com/127398804/224000978-6630d576-8fe6-44ce-bff9-5ceac2b8f269.png)
![image](https://user-images.githubusercontent.com/127398804/224001030-b0f60b65-712d-4e0e-a818-219081acb195.png)

**Comment by Mezryss** [comment]
Hmm... I haven't been able to reproduce this issue at all. 🤔

If you delete the talent through the XP Journal, do both go away or does one stick around?

**Comment by Assembling-Kings** [comment]
I have seen this happen again, usually when the passive has an empty activation.

**Comment by SheriffDann** [comment]
If you remove the talent via the XP journal it removes both.

To @Assembling-Kings point, if the talent as Active and at least one character in the field next to Activation, it only applies once.
![image](https://user-images.githubusercontent.com/127398804/224596873-69f7efea-415b-4e32-8ebb-5156d3d0400a.png)

**Comment by Mezryss** [comment]
Ah! Got it reproducing now, thanks! I think I know what's up, I'll go in and make some adjustments.

The fact that removing it via the XP journal removes both entries means it's definitely just a visual thing, so data shouldn't break when I release a fix!
