### ISSUE TITLE
Talent upgrading is too restrictive

### ISSUE THREAD

**Issue by Assembling-Kings** [Mezryss/FVTT-Genesys#40]
The title might sound too broad so I'll list the current problems with the character sheet and the talents tab.

1. If the amount of XP available matches exactly the amount of XP to upgrade a talent then it won't let you do it.
2. Once a ranked talent reaches effective tier 5 (or if it is originally tier 5) you can't upgrade its rank any more.
3. Related to above, if somehow a tier 5 talent upgrade is purchased then it isn't counted as taking an additional slot.

**Comment by Mezryss** [comment]
I'm not sure where this broke exactly, but as part of my work in the character sheet rewrite (#14) I'm planning to do an overhaul of the XP Journal in addition to rewriting the logic for Talents and rewriting the Special Abilities/Talents and Inventory tabs. I'll make sure things are resolved with this in that change. (Keeping issue open for now, just to keep it fresh in my mind)
