### ISSUE TITLE
Journal entries for skill upgrades are showing the wrong rank

### ISSUE THREAD

**Issue by Assembling-Kings** [Mezryss/FVTT-Genesys#42]
When upgrading a skill the journal logs the new rank as one higher than usual. The problem is in [[this line of code]](https://github.com/Mezryss/FVTT-Genesys/blob/main/src/vue/sheets/actor/character/SkillsTab.vue#L98) (notice that a few lines above it the rank was already increased so adding the `+1` is unnecessary.

Starting Sheet:
![image](https://user-images.githubusercontent.com/1728535/228321651-ad5215e6-d919-414e-bc90-24f9e3e7b432.png)

After buying 5 ranks in Athletics:
![image](https://user-images.githubusercontent.com/1728535/228321907-868c9235-ca96-4e63-83c6-c093d7af8c30.png)

Journal:
![image](https://user-images.githubusercontent.com/1728535/228321980-d2ffd555-d5a0-4e63-ad6f-03a51b28694f.png)

**Comment by Assembling-Kings** [comment]
The fix is easy as I mentioned above but I didn't make a pull request because I'm not sure if (or how) you want to do a migration to change all sheets already created.

**Comment by Mezryss** [comment]
Not sure where along the lines this broke, but as I mentioned in #40 the XP Journal is going to be getting an overhaul as part of the character sheet rewrite (#14) that I'm currently working on, so this should get resolved as part of that.
