### ISSUE TITLE
Ranked Talent effects don't stack per rank

### ISSUE THREAD

**Issue by thirionlogan** [Mezryss/FVTT-Genesys#44]
Ranked Talent effects don't stack per rank, for Example:
If I create the talent "Toughened" and add a passive effect that adds 2 to the wound threshold of a character, it will do so just fine for the first rank but won't do so for additional ranks.

![image](https://user-images.githubusercontent.com/73679754/235255237-8bd6edbe-5a6b-4a4c-a320-0395f247957e.png)

This should be 14:
![image](https://user-images.githubusercontent.com/73679754/235255324-bd6947c4-ce49-452a-b585-ee15ef6dddc5.png)

**Comment by JackDCondon** [comment]
Im pretty sure this is working as intended? As not every ranked talent will double its outputs? I would just edit it to plus 4 when you rank it up. Its a good idea to teach your players this stuff, its as critical as doodling reminders on your pen and paper sheet imo.

**Comment by JackDCondon** [comment]
Actually it would be great to be able to add an inline attribute for the item to use 2* {system.rank} so it would scale!  Not sure if this is supported but its worth a go.

**Comment by Mezryss** [comment]
> Im pretty sure this is working as intended? As not every ranked talent will double its outputs? I would just edit it to plus 4 when you rank it up. Its a good idea to teach your players this stuff, its as critical as doodling reminders on your pen and paper sheet imo.

No, the intent is that they should be applied per-rank. See `GenesysEffect#apply()`.

**Comment by thirionlogan** [comment]
Wow! Thanks for fixing this so quickly! As an aside, do you have any features or issues you aren't working on that I could pick up? I'd like to contribute to give back to a wonderful project, and I'm also planning on GMing a campaign soon 😁
