### ISSUE TITLE
Active Effects always on regardless of Equipped status

### ISSUE THREAD

**Issue by Lyinggod** [Mezryss/FVTT-Genesys#48]
Active Effects that are assigned to items stay active regardless of the equipped status of the effects item. This means that any item that is equipped, carried, or dropped still grants the effect. While these effects could be manually turned on or off, it is up to the character or GM to remember to do so.

Perhaps this could corrected by adding "minimum equipped" status as a drop down in the "data" tab. This would allow an effect to be applied when the equipped status is met

Example
If a cloak only grants melee defense, this must be set as an effect because defense is (currently) both melee and ranged. A combat situation results in the cloak falling off the wearer. By changing the cloak to "dropped", the effect would not apply until is move to an equipped status.

Example 2:
The cloak has been stuffed away in a backpack and is now in a "carried" status, so the possessor gets not benefit from the effect.

**Comment by Mezryss** [comment]
Tracked in #12
