### ISSUE TITLE
Initiative Rolls - option to 'lock' slot choices?  

### ISSUE THREAD

**Issue by Leonaquilla** [Mezryss/FVTT-Genesys#51]
Could we have a toggle that disables wiping each person from their initiative slots with a new round?  Or alternately just remembers each slot choice from round to round unless it's manually removed?

**Comment by Mezryss** [comment]
Sorry, this isn't something I'm interested in setting up. If I were to do this, I would want to do it in a way that offers a better user experience than the current flow for clearing a claimed initiative slot - and in the end, I don't think it's worth that effort.
