### ISSUE TITLE
Automatic dice pool modification from talents?

### ISSUE THREAD

**Issue by Ryminer2** [Mezryss/FVTT-Genesys#53]
If this is implemented I'm struggling to figure out how to make it work. It would be very convenient for talents to be able to make initial adjustments to dice pools, such as removing setbacks, adding boost dice, or upgrading ability when using certain skills. If this is unfeasible, at least allowing them to display icons next to skills as a reminder that you have talents which can potentially modify them in this way (in a fashion similar to SWRPG/the Oggdude character creator) would be nice too.

**Comment by Mezryss** [comment]
This is something I've been considering for future implementation, but at the soonest it would be in 1.4 work. If I ever actually reach that point, I haven't had much energy for working on this lately.
