### ISSUE TITLE
Free skill rank not displayed in Archetype description

### ISSUE THREAD

**Issue by Lyinggod** [Mezryss/FVTT-Genesys#56]
The archetype description does not show the starting skill rank. As archetypes usually provide a free rank in a specific skill, the only way to currently note this to the player is via a special ability entry. If one or more skills is present in the archetype's Granted Items list, the description should show this. This aligns the archetype description fully to the core archetype layout (AFAIK).

**Comment by Assembling-Kings** [comment]
I'm of the mind that this is better represented as a special ability. Some archetypes even have different verbiage with regards to the skill ranks they provide (like it must be a non-career skill, or the max level of a skill can be 3 instead of 2, etc).
