### ISSUE TITLE
Issue regarding clarity on how to Add modifires for to Talents, special Abilities, and item qualities.

### ISSUE THREAD

**Issue by Roxas21** [Mezryss/FVTT-Genesys#59]
When trying to add things, such as the item quality "Accurate" or "Superior" to a weapon I do not see where I can tell it to add a boost/Setback dice to attack rolls.

In the Talents and Special Abilities data section, there is an Activation option, which I will assume is how to activate the talent, but is there a place where I can see how to use this function?

Some Special Abilities might have an attack or challenge attached, is there a way to do this yet?

**Comment by Assembling-Kings** [comment]
> When trying to add things, such as the item quality "Accurate" or "Superior" to a weapon I do not see where I can tell it to add a boost/Setback dice to attack rolls.

Currently there is no way to add dice to any rolls via effects.

> In the Talents and Special Abilities data section, there is an Activation option, which I will assume is how to activate the talent, but is there a place where I can see how to use this function?

This refers how the talent/special ability is activated by a character. No additional functionality is tied to it.

> Some Special Abilities might have an attack or challenge attached, is there a way to do this yet?

There is no way to do this as of yet.
