### ISSUE TITLE
@sym/dice do not work in character sheet notes

### ISSUE THREAD

**Issue by Lyinggod** [Mezryss/FVTT-Genesys#66]
@sym/qdice do not work in character sheet notes. Please allow all character sheet text boxes to use dice/sym functionality.

**Comment by Assembling-Kings** [comment]
I just checked and they all allow the `@dice` and `@symbol` enrichers. Unless you mean the "Notable Features" box under the "Character Description" section, although that one is intended for a description of your character.

**Comment by NinjaPirateBob** [comment]
I feel like an idiot for asking but I couldn't find the right way to type the symbols and dice in the journals. Is there a reference sheet for the correct syntax or something I need to install first?

**Comment by Assembling-Kings** [comment]
> I feel like an idiot for asking but I couldn't find the right way to type the symbols and dice in the journals. Is there a reference sheet for the correct syntax or something I need to install first?

It's a fair question since I don't think it's said anywhere specifically. Check this discussion (https://github.com/Mezryss/FVTT-Genesys/discussions/50), specifically the "Dice Codes" section.
