### ISSUE TITLE
Images on Character/Item sheets can't be changed

### ISSUE THREAD

**Issue by superseva** [Mezryss/FVTT-Genesys#76]
When clicking to change the image on the sheets the selection popup doesn't appear

**Comment by Beiarusia** [comment]
I have also encountered this problem. Attempting to change the image does nothing. No selection pop-up, no error message, etc. 

I did try reverting back to Foundry Version 10 and did not get this problem so my only guess is a compatibility issue?

**Comment by RobHBlake** [comment]
Same problem here in Foundry V11.306. With or without modules activated.
No popup to change images on the actors sheets and items.
No problem in V10.

**Comment by SheriffDann** [comment]
I had the same issue, got around it using the Tokenizer Mod for now. Allows you to click the avatar image on the character sheet or edit via tokenizer in the actor library.

**Comment by falatorry** [comment]
Hi! I also have the same problem. However, it works in one case. The item's picture selection menu appears when you change the picture for the effect. There is also a problem with that menu, it appears twice.
