### ISSUE TITLE
Unable to make an effect which subtracts from a stat

### ISSUE THREAD

**Issue by thirionlogan** [Mezryss/FVTT-Genesys#83]
I tried to apply an effect to a character (due to a crit) which reduces their brawn by one (1) but there is no option in the "change mode" dropdown for "subtract"
![image](https://github.com/Mezryss/FVTT-Genesys/assets/73679754/18d062c8-5870-4ebb-8963-73d9d68c43fb)

**Comment by Assembling-Kings** [comment]
You can achieve this by using the `Add` "Change Mode" and providing a negative value for the "Effect Value".
